<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class InsertBarangays extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('barangays')->insert([
            ['name' => 'Barangay 1-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 2-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 3-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 4-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 5-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 6-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 7-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 8-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 9-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 10-A', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 11-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 12-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 13-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 14-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 15-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 16-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 17-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 18-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 19-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 20-B', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 21-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 22-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 23-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 24-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 25-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 26-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 27-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 28-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 29-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 30-C', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 31-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 32-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 33-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 34-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 35-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 36-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 37-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 38-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 39-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Barangay 40-D', 'district' => 'Poblacion District', 'delivery_charge' => '40'],
            ['name' => 'Agdao Proper', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Agdao Centro', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Gov. Paciano Bangoy', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Kap. Tomas Monteverde, Sr.', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Lapu-Lapu', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Leon Garcia', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Rafael Castillo', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'San Antonio', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Ubalde', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Wilfredo Quirino', 'district' => 'Agdao District', 'delivery_charge' => '40'],
            ['name' => 'Acacia', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Alfonso Angliongto', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Gov. Paciano Bangoy Sr.', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Buhangin Proper', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Cabantian', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Callawa', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Communal', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Indangan', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Mandug', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Pampanga', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Sasa', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Tigatto', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Vicente Hizon Sr.', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Waan', 'district' => 'Buhangin District', 'delivery_charge' => '40'],
            ['name' => 'Bago Aplaya', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Bago Gallera', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Baliok', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Bucana', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Catalunan Grande', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Catalunan Pequeno', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Dumoy', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Langub', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Maa', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Magtuod', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Matina Aplaya', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Crossing', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Matina Pangi', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Talomo Proper', 'district' => 'Talomo District', 'delivery_charge' => '50'],
            ['name' => 'Alambre', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Atan-Awe', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Bangkas Heights', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Baracatan', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Bato', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Daliao', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Daliaoan Plantation', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Eden', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Kilate', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Lizada', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Bayabas', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Binugao', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Camansi', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Catigan', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Crossing Bayabas', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Lubogan', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Marapangi', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Mulig', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Sibulan', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Sirawan', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Tagluno', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Tagurano', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Tibuloy', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Toril Proper', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Tungkalan', 'district' => 'Toril District', 'delivery_charge' => '65'],
            ['name' => 'Angalan', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Bago Oshiro', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Balengaeng', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Biao Escuela', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Biao Guinga', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Los Amigos', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Manambulan', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Manuel Guianga', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Matina Biao', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Mintal', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'New Carmen', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'New Valencia', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Santo Nino', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Tacunan', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Tagakpan', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Talandang', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Tugbok Proper', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Ula', 'district' => 'Tugbok District', 'delivery_charge' => '65'],
            ['name' => 'Alejandro Navarro (Lasang)', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Bunawan Proper', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Gatungan', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Ilang', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Mahayag', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Mudiang', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Panacan', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'San Isidro (Licanan)', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Tibungco', 'district' => 'Bunawan District', 'delivery_charge' => '65'],
            ['name' => 'Biao Joaquin', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Calinan Proper', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Cawayan', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Dacudao', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Dalagdag', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Dominga', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Inayangan', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Lacson', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Lamanan', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Lampianao', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Megkawayan', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Pangyan', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Riverside', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Saloy', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Sirib', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Subasta', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Talomo River', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Tamayong', 'district' => 'Calinan District', 'delivery_charge' => '115'],
            ['name' => 'Wangan', 'district' => 'Calinan District', 'delivery_charge' => '115'],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
